[package]
name = "fht2p"
version = "0.9.0-alpha" # alpha<alpha.1<beta<rc
authors = ["Wspsxing <biluohc@qq.com>"]
description = "A HTTP Server for Static File written with Rust"
build = "build.rs"
license = "MIT"

[workspace]

[profile.release]
opt-level = 3
lto = true
# debug = true 

[build-dependencies]
chrono  = { version = "0.4.6", features = ["serde"] }
askama = "0.7.2"
rsass = "0.9.2"

[dependencies]
signalfn = { version = "*", path = "./crates/signalfn" }

tokio = "0.1.11"
tokio-fs = "0.1.4"
tokio-rustls = "0.8.0"
tokio-retry = "0.2"
httparse = "1.3.2"
bytes = "0.4.10"
net2 = "0.2.33"
futures = "0.1.22"
num_cpus = "1.0"

http = "0.1.13"
hyper = "0.12.16"
mime_guess = "2.0.0-alpha.6"
askama = "0.7.2"
url = "1.6.0"

serde_derive = "1.0.80"
lazy_static = "1.2.0"
serde = "1.0.80"
json5 = "0.2.1"
fern = { version = "0.5.6", features = ["colored"] }
chrono  = { version = "0.4.6", features = ["serde"] }
bytesize = "1.0.0"
systemstat = "0.1.3"

failure = "0.1.2"
failure_derive = "0.1.2"
cfg-if = "0.1.5"
clap = "2.32"
log = "0.4.6"










